development:
  adapter: postgis
  encoding: unicode
  host: localhost
  username: opencensus_dev
  password: opencensus_dev
  database: opencensus_dev
  su_username: adam
  script_dir: /usr/share/postgresql/9.1/contrib/postgis-1.5/
  schema_search_path: public,postgis

test:
  adapter: postgis
  encoding: unicode
  host: localhost
  username: opencensus_test
  password: opencensus_test
  database: opencensus_test
  su_username: adam
  script_dir: /usr/share/postgresql/9.1/contrib/postgis-1.5/
  schema_search_path: public,postgis

production: 
  adapter: postgis
  encoding: unicode
  host: localhost
  username: opencensus_dev
  password: opencensus_dev
  database: opencensus_dev
  su_username: adam
  script_dir: /usr/share/postgresql/9.1/contrib/postgis-1.5/
  schema_search_path: public,postgis

#production:
#  adapter: postgis
#  encoding: unicode
#  host: localhost
#  username: opencensus_prod
#  password: opencensus_prod
#  database: opencensus_prod
#  su_username: adam
#  script_dir: /usr/share/postgresql/9.1/contrib/postgis-1.5/
#  schema_search_path: public,postgis
