development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: opencensus_dev
  password: opencensus_dev
  database: opencensus_dev

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: opencensus_test
  password: opencensus_test
  database: opencensus_test

production: 
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: opencensus_dev
  password: opencensus_dev
  database: opencensus_dev
